### PR TITLE
Project changes to allow consuming cordova as submodule

### PR DESCRIPTION
**Pull request by wmathurin**

### CODE REVIEW

**Review by bhariharan — APPROVED** [review]
@wmathurin Could we send an upstream PR and link it here as well?

**Comment by wmathurin** [comment]
@bhariharan it's only if consume cordova as a submodule - do they care to support that use case?

**Comment by bhariharan** [comment]
Well - the public headers should be consistent for framework and podspec, right?

**Comment by wmathurin** [comment]
May I didn't need the public header changes. Let me see.

**Comment by wmathurin** [comment]
Here is the PR for the apache/cordova-ios repo: https://github.com/apache/cordova-ios/pull/1015

**Pull request merged**
